# Dockerfile.nginx
FROM nginx:alpine

# Eliminar la configuración predeterminada de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiar la configuración personalizada
COPY nginx/conf.d/default.conf /etc/nginx/conf.d/

# Crear directorio para archivos estáticos
RUN mkdir -p /app/web/static

# Configurar permisos
RUN chown -R nginx:nginx /app/web/static

# Exponer puerto
EXPOSE 80